name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@12.9.0

      - name: Prepare files
        run: |
          mkdir -p public
          cp index.html public/
          # Copia pastas se existirem
          [ -d css ] && cp -r css public/
          [ -d js ] && cp -r js public/
          [ -d images ] && cp -r images public/

      - name: Replace environment secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_MASTER_KEY: ${{ secrets.JSONBIN_MASTER_KEY }}
          JSONBIN_ACCESS_KEY: ${{ secrets.JSONBIN_ACCESS_KEY }}
        run: |
          sed -i "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" public/index.html
          sed -i "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" public/index.html
          sed -i "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" public/index.html
          sed -i "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" public/index.html
          sed -i "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" public/index.html
          sed -i "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" public/index.html
          sed -i "s|%%JSONBIN_BIN_ID%%|$JSONBIN_BIN_ID|g" public/index.html
          sed -i "s|%%JSONBIN_MASTER_KEY%%|$JSONBIN_MASTER_KEY|g" public/index.html
          sed -i "s|%%JSONBIN_ACCESS_KEY%%|$JSONBIN_ACCESS_KEY|g" public/index.html

      - name: Debug (verificar substituições)
        run: |
          echo "Verificando substituições no index.html:"
          grep -E '%%[A-Z_]+%%' public/index.html || echo "Todas as variáveis foram substituídas com sucesso"

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "Iniciando deploy..."
          firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT_ID" --debug
