name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools@12.9.0
          firebase --version

      - name: Prepare deployment structure
        run: |
          # Cria estrutura de diretórios se necessário
          mkdir -p public
          # Copia arquivos para o diretório public
          if [ -f "index.html" ]; then
            cp -v index.html public/
          fi
          if [ -d "css" ]; then
            cp -rv css public/
          fi
          if [ -d "js" ]; then
            cp -rv js public/
          fi
          if [ -d "images" ]; then
            cp -rv images public/
          fi

      - name: Inject environment secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_MASTER_KEY: ${{ secrets.JSONBIN_MASTER_KEY }}
          JSONBIN_ACCESS_KEY: ${{ secrets.JSONBIN_ACCESS_KEY }}
        run: |
          echo "Substituindo variáveis no index.html..."
          sed -i "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" public/index.html
          sed -i "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" public/index.html
          sed -i "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" public/index.html
          sed -i "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" public/index.html
          sed -i "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" public/index.html
          sed -i "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" public/index.html
          sed -i "s|%%JSONBIN_BIN_ID%%|$JSONBIN_BIN_ID|g" public/index.html
          sed -i "s|%%JSONBIN_MASTER_KEY%%|$JSONBIN_MASTER_KEY|g" public/index.html
          sed -i "s|%%JSONBIN_ACCESS_KEY%%|$JSONBIN_ACCESS_KEY|g" public/index.html
          
          echo "Verificando substituições..."
          if grep -q '%%' public/index.html; then
            echo "::error::Placeholders não substituídos encontrados!"
            grep -n '%%' public/index.html
            exit 1
          fi

      - name: Validate deployment
        run: |
          echo "Estrutura final:"
          ls -la public/
          echo -e "\nConteúdo inicial do index.html:"
          head -n 10 public/index.html

      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT_ID }}
