name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (minimal)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          # Removida a configuração de cache para evitar o aviso

      - name: Create minimal package.json
        run: |
          if [ ! -f "package.json" ]; then
            echo '{"name":"backlogeqtl","private":true}' > package.json
            echo "Arquivo package.json mínimo criado"
          fi

      - name: Install Firebase CLI (sem lockfile)
        run: |
          echo "Instalando Firebase CLI..."
          npm install --global --no-package-lock firebase-tools@12.9.0
          echo "Versão do Firebase: $(firebase --version)"

      - name: Prepare deployment files
        run: |
          mkdir -p public
          if [ -f "index.html" ]; then
            cp index.html public/
            echo "✓ index.html copiado para public/"
          elif [ -f "public/index.html" ]; then
            echo "✓ index.html já está no diretório public/"
          else
            echo "::error::index.html não encontrado!"
            exit 1
          fi

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
